---
- name: Create App Service Plan
  azure_rm_appserviceplan:
    resource_group: "{{ resource_group }}"
    name: "{{ myAppServicePlan }}"
    location: "{{ location }}"
    is_linux: true
    sku: FREE

- name: Create a Linux web app with PHP
  azure_rm_webapp:
    resource_group: "{{ resource_group }}"
    name: "{{ webapp_name }}"
    plan:
      resource_group: "{{ resource_group }}"
      name: "{{ myAppServicePlan }}"
    app_settings:
      testkey: "testvalue"
    frameworks:
      - name: "php"
        version: "7.3"

- name: Login to Azure
  shell: az login -u {{ AZ_User }} -p {{ AZ_Pass }}

- name: "Add Connection String to MySQL"
  shell: az webapp config connection-string set -g {{ resource_group }} -n {{ webapp_name }} -t MySql --settings HOST={{ mysqlserver_name }}.mysql.database.azure.com USER={{ admin_username }}@{{ mysqlserver_name }} PASSWORD={{ admin_password }}

...